### ISSUE TITLE
[SyntaxError] print "FOUND: %s, updating gpodder database" % (row2)

### ISSUE THREAD

**Issue by galantra** [sairuk/gpodder_pc_import#1]
I'm trying to migrate from Podcast Addict to AntennaPod and gPodder. I use Windows 10 and gPodder Portable from PortableApps.com

I'm following this [instruction](http://www.mameau.com/gpodder-podcast-import-script/). I made sure that my python is set up correctly, especially the PATH system variable.

I got to step 4 and ran the script. This raised the following error:

```
C:\Users\user\PortableApps\gPodderPortable\Data\config\Downloads>python main.py
  File "main.py", line 70
    print "FOUND: %s, updating gpodder database" % (row2)
                                               ^
SyntaxError: invalid syntax

C:\Users\user\PortableApps\gPodderPortable\Data\config\Downloads>python main.py
  File "main.py", line 70
    print "FOUND: %s, updating gpodder database" % (row2)
                                               ^
SyntaxError: invalid syntax

C:\Users\user\PortableApps\gPodderPortable\Data\config\Downloads>python main.py
  File "main.py", line 70
    print "FOUND: %s, updating gpodder database" % (row2)
                                               ^
SyntaxError: invalid syntax
```

**Comment by sairuk** [comment]
What version of python are you using? Based on the date this was raised i expect this is a python 3 issue.

This script was created long before python3 was the norm

**Comment by sairuk** [comment]
I've committed an update for python3, please grab it and test the latest version and provide feedback I haven't used podcast addict in a long time

**Comment by galantra** [comment]
Here is what I did wrong: I placed _main.py_ in the _Downloads_ directory, not in _config_.
